// converts projects/raw-md-files/**/*.md into static json + html the site can use

import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseMarkdown, slugify, stripHtml } from './md.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'projects', 'raw-md-files');
const OUT = path.join(ROOT, 'projects', 'data');
const PROJECTS = path.join(ROOT, 'projects');

const RESERVED = new Set(['data', 'raw-md-files']);

// collect .md files recursive, ignores a bunch of junk files from my os
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(full)));
    else if (e.name.toLowerCase().endsWith('.md')) files.push(full);
  }
  return files;
}

// [name]/index.md -> "[name]"
function slugFor(file) {
  const rel = path.relative(SRC, file).replace(/\.md$/i, '');
  const parts = rel.split(path.sep);
  if (parts[parts.length - 1].toLowerCase() === 'index') parts.pop();
  return slugify(parts.join('-')) || 'index-page';
}

const escapeAttr = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

function renderToc(headings) {
  const items = headings.filter((h) => h.level >= 2 && h.level <= 3);
  if (items.length === 0) return '';
  const links = items
    .map(
      (h) =>
        `        <li class="toc--l${h.level}"><a href="#${escapeAttr(h.id)}">${escapeAttr(h.text)}</a></li>`
    )
    .join('\n');
  return `      <aside class="doc-toc" aria-label="On this page">
        <p class="doc-toc__title">On this page</p>
        <ul>
${links}
        </ul>
      </aside>`;
}

function renderPage({ slug, title, description, doc, source }) {
  const safeTitle = escapeAttr(title);
  const safeDesc = escapeAttr(description);
  const pageUrl = `/projects/${slug}/`;
  const toc = renderToc(doc.headings);
  const fm = doc.frontmatter || {};
  const byline = fm.author ? `<p class="doc-byline">by ${escapeAttr(String(fm.author))}</p>` : '';

  return `<!DOCTYPE html>
<!-- generated by scripts/build-content.mjs from ${source} — do not edit by hand -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${safeTitle} - Member Conlangs - Conlang Club @ UCSD</title>
<meta name="description" content="${safeDesc}">
<link rel="icon" href="../../assets/logo.png" type="image/webp">
<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="${safeTitle} - Member Conlangs - Conlang Club @ UCSD">
<meta property="og:description" content="${safeDesc}">
<meta property="og:type" content="article">
<meta property="og:image" content="/assets/logo.png">
<meta property="og:url" content="${pageUrl}">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="${safeTitle} - Member Conlangs - Conlang Club @ UCSD">
<meta name="twitter:description" content="${safeDesc}">
<meta name="twitter:image" content="/assets/logo.png">
<style>
.doc-layout{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:36px;align-items:start}
@media(max-width:900px){.doc-layout{grid-template-columns:1fr}}
.doc-toc{position:sticky;top:96px;max-height:calc(100vh - 96px - 24px);overflow-y:auto;overscroll-behavior:contain;background:var(--paper);border:var(--line) solid var(--ink);border-radius:var(--radius);padding:18px 18px 14px;box-shadow:var(--shadow-off) var(--shadow-off) 0 0 var(--ink);font-size:.92rem}
@media(max-width:900px){.doc-toc{position:static;order:-1;max-height:320px}}
.doc-toc__title{font-family:var(--font-display);font-weight:700;margin:0 0 8px}
.doc-toc ul{list-style:none;margin:0;padding:0;display:grid;gap:6px}
.doc-toc a{color:var(--purple-deep);text-decoration:none}
.doc-toc a:hover{text-decoration:underline}
.toc--l3{padding-left:14px}
.doc-byline{color:var(--purple-deep);font-style:italic;margin:0 0 18px}
.prose{min-width:0;overflow-wrap:anywhere}
.prose h2,.prose h3,.prose h4{scroll-margin-top:90px}
.prose h2{margin-top:1.8em;padding-top:.4em;border-top:3px solid var(--ink)}
.prose h2:first-child,.prose h3:first-child{margin-top:0;border-top:0;padding-top:0}
.prose p,.prose ul,.prose ol,.prose blockquote,.prose pre{max-width:68ch}
.prose a{overflow-wrap:anywhere}
.prose pre{background:#17110f;color:#FFF6E7;border:var(--line) solid var(--ink);border-radius:var(--radius);padding:16px 18px;overflow:auto;font-size:.88rem;line-height:1.55;box-shadow:var(--shadow-off) var(--shadow-off) 0 0 var(--ink)}
.prose pre code{background:none;color:inherit;padding:0;border:0}
.prose code{font-family:'IBM Plex Sans',ui-monospace,monospace;background:#f1e4c8;border:1px solid rgba(23,17,15,.25);border-radius:6px;padding:.1em .35em;font-size:.9em}
.prose blockquote{margin:1.4em 0;padding:12px 18px;border-left:6px solid var(--gold);background:var(--paper);border-top:var(--line) solid var(--ink);border-right:var(--line) solid var(--ink);border-bottom:var(--line) solid var(--ink);border-radius:0 var(--radius) var(--radius) 0}
.prose blockquote p:last-child{margin-bottom:0}
.prose hr{border:0;border-top:3px dashed rgba(23,17,15,.35);margin:2.2em 0}
.prose img{border:var(--line) solid var(--ink);border-radius:var(--radius);box-shadow:var(--shadow-off) var(--shadow-off) 0 0 var(--ink)}
.prose table{width:100%;border-collapse:collapse;background:var(--paper);font-size:.93rem}
.prose th,.prose td{border:2px solid var(--ink);padding:8px 10px;text-align:left;vertical-align:top}
.prose thead th{background:var(--gold);font-family:var(--font-display)}
.prose tbody tr:nth-child(even) td{background:#fff8ec}
.table-wrap{overflow-x:auto;border:var(--line) solid var(--ink);border-radius:var(--radius);box-shadow:var(--shadow-off) var(--shadow-off) 0 0 var(--ink);margin:1.4em 0}
.table-wrap table{margin:0}
.table-wrap .table-wrap,.prose .table-wrap table{border:0;box-shadow:none}
.prose ul,.prose ol{padding-left:1.4em}
.prose li+li{margin-top:.3em}
</style>
</head>
<body>

<div data-include="header"></div>

<main>

  <div class="page-banner">
    <div class="wrap">
      <span class="hero-eyebrow">Member conlang</span>
      <h1>${safeTitle}</h1>
      ${description ? `<p>${safeDesc}</p>` : ''}
      ${byline}
    </div>
  </div>

  <section class="section-cream">
    <div class="wrap doc-layout">
      <article class="prose">
${doc.html}
      </article>
${toc}
    </div>
  </section>

  <section class="section-gold">
    <div class="wrap" style="text-align:center;">
      <h2 style="max-width:36ch; margin:0 auto 12px;">Building your own conlang?</h2>
      <p style="margin:0 auto 22px; max-width:46ch;"><a class="btn btn--small" href="../">Back to member conlangs</a></p>
      <a class="btn" href="https://discord.gg/PdkpT26AHG" target="_blank" rel="noopener">Share it in Discord</a>
    </div>
  </section>

</main>

<div data-include="footer"></div>

<script src="../../script.js"></script>
</body>
</html>
`;
}

async function removeStalePages(validSlugs) {
  let entries = [];
  try {
    entries = await readdir(PROJECTS, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (RESERVED.has(e.name)) continue;
    if (validSlugs.has(e.name)) continue;
    const indexFile = path.join(PROJECTS, e.name, 'index.html');
    let content = '';
    try {
      content = await readFile(indexFile, 'utf8');
    } catch {
      continue;
    }
    if (content.includes('generated by scripts/build-content.mjs')) {
      await rm(path.join(PROJECTS, e.name), { recursive: true, force: true });
      console.log(`  removed stale projects/${e.name}/`);
    }
  }
}

async function main() {
  const files = (await walk(SRC)).sort();
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const manifest = [];
  const seen = new Set();

  for (const file of files) {
    const slug = slugFor(file);
    if (RESERVED.has(slug)) {
      throw new Error(`Slug "${slug}" from ${path.relative(ROOT, file)} collides with reserved projects/${slug}/`);
    }
    if (seen.has(slug)) throw new Error(`Duplicate slug "${slug}" from ${path.relative(ROOT, file)}`);
    seen.add(slug);

    const raw = await readFile(file, 'utf8');
    const doc = parseMarkdown(raw);
    const title = doc.frontmatter.title || doc.title || slug;
    const description =
      doc.frontmatter.description || doc.frontmatter.excerpt || doc.excerpt || stripHtml(doc.html).slice(0, 240);
    const source = path.relative(ROOT, file).split(path.sep).join('/');
    const author = doc.frontmatter.author || doc.frontmatter.by || '';
    const entry = {
      slug,
      title,
      ...(author ? { author: String(author) } : {}),
      excerpt: description.slice(0, 240),
      source,
      url: `/projects/data/${slug}.json`,
      page: `/projects/${slug}/`,
    };

    await writeFile(path.join(OUT, `${slug}.json`), JSON.stringify({ ...entry, ...doc }, null, 2) + '\n');

    const html = renderPage({ slug, title, description: entry.excerpt, doc, source });
    const dir = path.join(PROJECTS, slug);
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, 'index.html'), html);

    manifest.push(entry);
    console.log(`  ${entry.source} -> projects/data/${slug}.json + projects/${slug}/index.html`);
  }

  await removeStalePages(seen);

  await writeFile(path.join(OUT, 'index.json'), JSON.stringify({ projects: manifest }, null, 2) + '\n');
  console.log(`Built ${manifest.length} page(s) + index.json + ${manifest.length} html page(s)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
